name: "Check Quay Image"
description: "Polls Quay.io to check if image with a given commit SHA exists."
inputs:
  quay_repo:
    description: "Quay repository in format namespace/repo"
    required: true
  commit_sha:
    description: "Commit SHA to check for as image tag"
    required: true
  quay_private:
    description: "Set to 'true' if the Quay repo is private"
    required: false
    default: "false"
  quay_token:
    description: "Quay API token (if private repo)"
    required: false
  delay_minutes:
    description: "Initial delay before first check (default: 10)"
    required: false
    default: "10"
  retries:
    description: "Number of retries (default: 20)"
    required: false
    default: "20"
  interval_minutes:
    description: "Minutes between retries (default: 1)"
    required: false
    default: "1"
  slack_webhook_url:
    description: "Slack Webhook URL to send notification on failure"
    required: false


runs:
  using: "composite"
  steps:
    - name: Checkout main repository
      uses: actions/checkout@v2
    - run: ./entrypoint.sh
      shell: bash
      env:
        QUAY_REPO: ${{ inputs.quay_repo }}
        COMMIT_SHA: ${{ inputs.commit_sha }}
        QUAY_PRIVATE: ${{ inputs.quay_private }}
        QUAY_TOKEN: ${{ inputs.quay_token }}
        DELAY_MINUTES: ${{ inputs.delay_minutes }}
        RETRIES: ${{ inputs.retries }}
        INTERVAL_MINUTES: ${{ inputs.interval_minutes }}
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        GITHUB_PR_URL: ${{ github.event.pull_request.html_url }}
        PR_MERGED: ${{ github.event.pull_request.merged }}
