name: Test Check Quay Image Action - FAIL

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-image:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Quay image
        uses: petracihalova/check-quay-image@v1
        with:
          quay_repo: redhat-services-prod/hcc-accessmanagement-tenant/insights-rbac
          commit_sha: ${{ github.sha }}
          delay_minutes: 1
          retries: 2
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
